name: 'Create a pull request'
description: 'Create a pull request in the current repo'
inputs:
  target_branch:  # id of input
    description: 'Branch to pull request'
    required: true
    default: ''
  secret_token:  # id of input
    description: 'Github token'
    required: true
    default: ''
outputs:
  log: # id of output
    description: 'Log info'
runs:
  using: 'node12'
  main: 'dist/index.js'
