name: 'Update image and create a pull request'
description: >
  Using state repo structure it updates an image value and the creates 
  a pull request in the same state repo
inputs:
  input_matrix:
    description: >
      Inputs in the format:
        {
          "images": [
            {
              "tenant": "tenant1",
              "app": "reportApp",
              "env": "dev",
              "service_name": "proxy",
              "image": "image_proxy:tag",
              "reviewers": ["userName"],
              // optional
              "base_folder": "apps"
            },
            {
              "tenant": "tenant1",
              "app": "pollingApp",
              "env": "pre",
              "service_name": "dns",
              "image": "image_dns:tag",
              "reviewers": ["userName"],
              // optional
              "base_folder": "apps"
            }
          ]
        }
    required: true
  token:
    description: >
      (Default value should not be messed with)
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'dist/index.js'
