name: 'Create a pull request'
description: 'Create a pull request in the current repo'
inputs:
  target_branch:
    description: 'Branch to pull request'
    required: true
    default: ''
  secret_token:
    description: 'Github token'
    required: true
    default: ''
  pr_title:
    description: 'The title of the PR'
    required: false
    default: 'PR title'
  application:
    description: 'Application to read from config.yaml'
    required: true
    default: ''
  environment:
    description: 'Environment to select from config.yaml'
    required: true
    default: ''
  reviewers:
    description: 'Rreviewers of the new PR'
    required: false
    default: ''

runs:
  using: 'node12'
  main: 'dist/index.js'
